# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: Linux2-Pool
 #name: Linux-Pool
 #demands:
  #- agent.name -equals agent2a
  #vmImage: agent1a

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'MyWebApp/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
